name: Naukri Profile Update 

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution from GitHub

jobs:
  update_naukri_profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure this matches your local version

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb  # Install Xvfb

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Start Virtual Display (Xvfb)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # Start virtual display in background
          export DISPLAY=:99  # Set the display environment variable

      - name: Run Selenium Script
        env:
          EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python naukri_update.py
